### ISSUE TITLE
如何更好的分离业务逻辑

### ISSUE THREAD

**Issue by Icedroid** [sdgmf/go-project-sample#1]
https://www.infoq.cn/article/4TAWp8YNYcVD4t046EGd
阅读这篇文章过来，跟文章中的改进：分离业务逻辑这一层还有点差距

**Comment by sdgmf** [comment]
我理解的文章的分离业务逻辑是把存储层分离出来，我不知道你指的是否是这个。

go-project-sample已经有独立的存储层，并且面向接口设计了，可以通过增加接口DetailsRepository的cache实现来扩展。
包的命名方式确实有所不同，因为文章中的方式还没有实践过,所以还不好说哪种更好。
